### PR TITLE
Add store version cookie

### PR DESCRIPTION
**Pull request by igorframos**
This is the first solution to split traffic between IO and Fast Store.

### CODE REVIEW

**Review by heynemann — CHANGES_REQUESTED** [review]
This won't works since this is the open source version. What does work and I intended to do previously is removing the hard-coded version and instead having a configuration with the path to the template file. WDYT? Want to do it?

**Comment by cezarguimaraes** [comment]
Another reason why this won't work is that all these `add_header` will actually be ignored when nginx chooses a more specific location than `location /`. Since we have `cache`/`preload` headers generated for every asset by the plugin, this will be the case every time. 
This could be done on the gatsby plugin side https://github.com/vtex/faststore/tree/master/packages/gatsby-plugin-vtex-nginx
I will soon add the possibility of adding headers through plugin options/env vars, so we could then add this one in the build task @ https://github.com/vtex/io-sre-konfig/blob/master/builders/004-gatsby-build/003-tasks/002-gatsby-build.yml#L29

On another note, should hyper-cas trouble itself with nginx config generation?

**Comment by heynemann** [comment]
Maybe not for locations, but for the main nginx conf, definitely, otherwise how would you know which tree is which label?

**Comment by cezarguimaraes** [comment]
Should it even be the one responsible for handling the label abstraction? The current code I wrote to use hyper-cas in our pipeline completely disregards friendly labels for two reasons:

1. I wanted the same pod to answer for `account.domain` and `distro-<hash>.domain` so I had to scratch the `server_name` directive.
2. If we set-label `master--account` for a broken build (which we won't know about until we try and launch a nginx after setting a label for that distro), this would side-effect the current deployments. So new pods for master would try and use this broken distro.

What I ended up doing was setting up a label that is exactly the distro hash, then updating the friendly labeled service to refer to that `<distro-hash>.conf` when starting up. This way we won't side-effect existing deployments, and if this revision fails to start up, knative won't route service traffic to it.

In the end we will need an API that handles routes (labels) to distros anyway for a/b testing, rollback, green/blue so I think it would be more complicated to also have to deal with hyper-cas label system and reloading nginx pods in tandem to account for label updates.

**Comment by igorframos** [comment]
The `add_header` directive will work the same way our `Hyper-Cas-Hash` and `Hyper-Cas-Label` work, they are at the `server` level, not `location`, which means they are added regardless of the matching location unless you are completely ignoring this `server` directive. Are you?

Regarding the labels, there is a lot of leeway here. Personally, I was inclined towards something less coupled to NGINX, even if NGINX is going to be part of the solution, though I understand it is a bit faster to start like this. Part of what you are saying, @cezarguimaraes, seems to be specific to our use case, but we should not need to completely rewrite the config.

**Comment by cezarguimaraes** [comment]
@igorframos Regarding the headers, the other ones don’t work either. From the nginx documentation:

`There could be several add_header directives. These directives are inherited from the previous configuration level if and only if there are no add_header directives defined on the current level. `

**Comment by igorframos** [comment]
> @igorframos Regarding the headers, the other ones don’t work either. From the nginx documentation:
> 
> `There could be several add_header directives. These directives are inherited from the previous configuration level if and only if there are no add_header directives defined on the current level. `

I had no idea it ignored all other `add_header`. 😮 Also, I did not like it. :chloe:

Then there is no point in doing it here, but we need to figure out a way actually *adding* headers instead of replacing everything defined by the higher level config. I will close the Pull Request, as it makes no sense in the end. I will try to figure out the best place to put my cookie. 🍪 Or I'll have to speed up the other solution I am intended to replace this one.

**Comment by cezarguimaraes** [comment]
Yep, that caught me off guard too and I think that's another reason for the nginx generation to be centralized by the plugin.

**Comment by igorframos** [comment]
> Yep, that caught me off guard too and I think that's another reason for the nginx generation to be centralized by the plugin.

I don't agree 100% with that, but at the same time I don't disagree entirely either. Generating an NGINX config here is coupling the CAS to the option of using NGINX over anything else one would want to put in front of it, so I think it is wrong given our less-opinionated approach in this iteration. On the other hand, the CAS has to have some power over the routing, so whatever you are doing down below, it should still be subject to what is being done in this layer. I need to think so I can form a better opinion and have better arguments to discuss because, as of now, I am yet to catch up on how this code works.

**Pull request closed without merging**
